AngelPM9506/PF-SoyHenry

next.config.js, package-lock.json, package.json, src/pages/_app.tsx, src/pages/api/auth/[...auth0].ts, src/pages/index.tsx
**next.config.js**: Allowlisted the google domain for the Gmail profile pictures to use within the Image component.
**_app.tsx**: Added the User Provider from Auth0
**/pages/api/auth/[...auth0].ts**: Added Auth0 component to handle login and logout
**index.tsx**: Removed the main boilerplate and added a simple Login, Logout, and Profile link just to test Auth0 and check that everything is working fine for everyone.
=> US1 - WT37 Config Auth0

prisma/schema.prisma, src/pages/api/trips/[id].tsx, src/pages/api/trips/index.ts, src/pages/api/users/[id].tsx, src/pages/api/users/index.tsx, src/utils/interface.ts, tsconfig.json
Listo para revisión Modelo y rutas de Usuarios
=> Modelo User y Routas Users

src/pages/api/cities/index.tsx
=> inicio de citites prueba

prisma/schema.prisma, src/pages/api/activities/[id].tsx, src/pages/api/activities/index.tsx, src/pages/api/trips/[id].tsx, src/utils/interface.ts
=> Rutas de activities lista falta delete por comprobar

src/pages/_app.tsx, src/pages/api/activities/index.tsx, src/utils/interface.ts
=> Filtros de Activities listos

src/components/TripCard.tsx, src/components/pagination/index.tsx, src/pages/trips.tsx
added pagging in trips page and layout
=> Us4    wt58 page trips paging

prisma/schema.prisma, src/pages/api/trips/[id].tsx, src/pages/api/trips/index.ts
Hice la relacion n : m entre actividades y trips y cree la tabla intermedia (activitiesOnTrips)
=> Relacion en modelos activity/trips

src/pages/api/trips/[id].tsx, src/pages/api/trips/index.ts
Hice la relacion viajes/usuarios. En la ruta put[id] de trips se pueden agregar usuarios al viaje y en la ruta get[id] del viaje devuelve los viajes con los respectivos usuarios anotados
=> Relation trips/traveleres

src/components/TripDetail.tsx, src/pages/trips/[id].tsx, src/pages/trips/index.tsx
made page and component of the detail, 
also Linked the trips page with the thip detail pages and change the location of the file trips page
=> Trip detail component and page

src/components/TripDetail.tsx
update component detail and fixed redirecting
=> info charged on detail

src/pages/api/activities/index.tsx
Arreglo del error en la ruta post
=> Arreglo de errores ruta post activities

src/components/UserProfile.tsx, src/components/layout/Nav.tsx, src/pages/activities/index.tsx, src/pages/api/activities/index.tsx, src/pages/api/auth/[...auth0].ts, src/utils/interface.ts
Fix navbar links to be SPA links (using next/link)
=> Fix navbar

package-lock.json, src/pages/trips/create.tsx, src/utils/interface.ts
He agregado funcionalidades para que el usuario pueda eliminar cities o activities si así lo desea...
=> Refactoring create form

src/pages/trips/index.tsx, src/utils/trips.ts
create a button on trips page to redirect to create new trip 
made the conections and settings for the filters to work
fix the css of the filters
=> Filters of trips page

src/components/ActivityCard.tsx, src/components/ActivityDetail.tsx, src/components/ActivityFilters.tsx, src/components/layout/Nav.tsx, src/components/miniCardActivity.tsx, src/pages/activities/[id].tsx, src/pages/activities/index.tsx, src/pages/trips/create.tsx, src/utils/activities.ts
Create activity details page and component
=> Activity Detail

src/pages/api/trips/index.ts
=> Filter trips by cities

src/pages/index.tsx
changes in the container of the video and video settings of landingPage
=> image change from cloudinary / settings container

src/components/UserProfile.tsx, src/pages/api/users/[id].tsx, src/utils/cloudinaryUpload.ts
Fixed the error after updating the user profile without changing the image
=> Fix userprofile put

src/pages/404.js
create the page 404 not found and linked it to the home to redirect
=> 404 page not found

src/pages/index.tsx, src/pages/trips/create.tsx
I've made a new design of the landing page
=> New design landing page

src/components/TripDetail.tsx, src/components/miniCardActivity.tsx, src/pages/trips/[id].tsx, src/utils/trips.ts
trip detail 
now it shows the information correctly : 
the activities asociated and also the cities.
=> trip detail show info correct

src/components/TripCard.tsx, src/components/TripDetail.tsx, src/components/miniCardActivity.tsx, src/pages/trips/create.tsx, src/pages/trips/index.tsx
Rearrange of the create form , css 
in next pull request i will fix button X of activity that doesnt work correctly ( it erases the name but the price remains and i cant choose it again once it is erased.)
=> Trip detail update agustina

package.json, src/components/Carousel.tsx, src/utils/SettingsCarousel.ts, src/utils/interface.ts
He rediseñado el home con dos carousels que se adecúan a nuestra idea inicial.. además responsive.. edité interfaces y agregué las configuraciones del carousel en un nuevo archivo para así cambiarlas a nuestro gusto cada vez que queramos y como queramos..
=> New carousel

src/components/ActivityCard.tsx, src/components/ActivityDetail.tsx, src/components/TripCard.tsx, src/pages/activities/index.tsx
css activities and activity detail
=> css activity detail and page

src/components/Carousel.tsx, src/controllers/activities.ts, src/controllers/trips.ts, src/pages/activities/create.tsx, src/pages/home.tsx, src/pages/index.tsx, src/pages/trips/create.tsx, src/pages/trips/index.tsx
fix the create form of trips and activities, 
(modified files controlers trip and activities and create trip and activities)
and center carousels in home page.
=> Fix create trip and create activity and home css

src/pages/index.tsx, src/pages/trips/create.tsx, src/utils/interface.ts, src/utils/validations.ts
video of landing reproduce when mouse move
=> onMouseMove video landingpage

src/components/UserDetail.tsx, src/components/layout/Footer.tsx, src/components/layout/Nav.tsx, src/pages/api/users/index.tsx
He agregado acceso al perfil publico y mejorado aspectos de estilos
=> Setting nav to public profile access

src/pages/activities/[id].tsx, src/pages/trips/[id].tsx, src/pages/user/[id].tsx
change the static to serversideprops - users detail - trips detail and activities detail .
build working
=> users,trips,activitys detail working dynamic

prisma/schema.prisma, src/components/TimeLineTrip.tsx, src/pages/api/payment/paypal/index.tsx
en la ruta trips/[id] creamos la conexion con paypal | corrimos npm run build y paso todo con exito
=> Paypal integration

src/components/TimeLineTrip.tsx, src/controllers/users.ts, src/pages/api/payment/paypal/index.tsx, src/pages/api/users/[id].tsx, src/pages/api/users/index.tsx, src/utils/searchUserOnTrip.tsx
Configuramos el botón de párasela de pagos de un trip.
=> Payment trips

prisma/schema.prisma, src/controllers/trips.ts, src/pages/api/trips/index.tsx, src/utils/interface.ts
Agregue actDate a la tabla intermedia activitiesOnTrips, cuando se hace un get del detalle del trip, trae las actividades que tiene y la fecha en la que se hace. Y en el post la info debe viajar : activitiesName:{ name : string, actDate : string } 💯
=> add actDate

prisma/schema.prisma, src/controllers/activities.ts, src/pages/api/activities/[id].tsx
Ruta put y delete de los feedbacks, en la ruta put debe recibir el idFeedback y comentario por body y en la ruta delete el idFeedback
=> Delete put feedbak

prisma/schema.prisma, src/controllers/activities.ts
El feedback quedo en un mismo objeto
=> reformateo del patch del feedback

src/components/TripAvatarCarousel.tsx, src/components/UserDetail.tsx, src/components/UserProfile.tsx, src/pages/trips/create.tsx, src/pages/user/[id].tsx, src/utils/TripAvatarCarouselSettings.ts, src/utils/interface.ts
I've rendered more details in userDetails.
=> Public profile renderizar viajes creados y viajes a los que es parte

package.json, src/components/layout/Nav.tsx, src/controllers/users.ts, src/pages/api/payment/paypal/index.tsx, src/pages/user/my-trips.tsx, src/styles/globals.css, src/utils/User.ts
in the route user/my-trips render the table with my trips
=> route user/my-trips complete

src/components/ActivityDetail.tsx, src/components/Reviews.tsx, src/components/TimeLineTrip.tsx, src/components/reviews/reviews.tsx
toast and css to comments 
change message of trip detail
=> css and toast comments

package.json, src/pages/trips/create.tsx
He configurado el toast considerando que pudiese ocurrir un error, he seteado el input date de las actividades, ahora solo disponible con los días de la actividad.. he corregido algunos estilos.. :) 😁👌
=> Fixing input dates of activities in create trip form

src/pages/api/activities/[id].tsx, src/pages/user/admin.tsx, src/utils/activities.ts
added a conditional to convert the idFeedback property to string only when it exists
=> Fix put activities

src/components/ActivityFilters.tsx, src/components/ActivityTable.tsx, src/components/Banned.tsx, src/components/UserTable.tsx, src/components/layout/Nav.tsx, src/controllers/activities.ts, src/pages/activities/[id].tsx, src/pages/activities/create.tsx, src/pages/activities/index.tsx, src/pages/api/activities/[id].tsx, src/pages/home.tsx, src/pages/trips/create.tsx, src/pages/trips/index.tsx, src/pages/user/admin.tsx, src/pages/user/my-trips.tsx, src/pages/user/profile.tsx, src/utils/activities.ts
Added message for banned users & restricted access everywhere
Fix activity delete route
Added multi select for availability in activities creation
Improved cities selection ux in activities creation
replaced loading messages with the loading spinner
fixed "no data" message in activities detail
added "active link" to navbar
remove "reset" button from max price filter in the activities page
added reset results option to "all activities" page when there's no data
some css fixes
=> Banned users msg + fix some stuff

src/components/ActivityCard.tsx, src/components/Carousel.tsx, src/components/TripCard.tsx, src/components/layout/Nav.tsx, src/pages/activities/index.tsx, src/pages/trips/index.tsx
He configurado algunas funcionalidades, mejorado aspectos de estilos y corregido performance usando nextlink donde era necesario..
=> Checking the list details we wrote

src/controllers/trips.ts, src/pages/trips/create.tsx
=> Fix trips create

src/components/layout/Footer.tsx, src/components/layout/Layout.tsx, src/components/layout/Nav.tsx
He rediseñado el NavBar y Footer y se hizo responsive..
=> Nav bar   footer   layout

src/pages/index.tsx
Landing Page added bottons for contact us and about us, switch sound and made it responsive
=> Landingpage fix sprint 3

src/pages/index.tsx, src/styles/landing.module.css
landing page css completed 
video full viewport 
mute and volume up botton 
bottons
=> css landing page done

src/components/AboutCarousel.tsx, src/pages/about/index.tsx, src/pages/index.tsx, src/utils/aboutCards.ts
=> New about page

src/components/CardTimeLine.tsx, src/components/layout/Layout.tsx, src/pages/404.tsx, src/pages/index.tsx
404 responsive 
layout min height 100 vh
=> 404 page responsive

src/components/UserDetail.tsx
He corregido el renderizado condicionando en función a si creó o no viajes, si se unió o no a algún viaje..
=> Fixing render of associated trips

src/components/UserProfile.tsx, src/utils/validations.ts
Diseño responsive y validaciones...
=> Responsive design and validations of profile update

src/pages/trips/index.tsx
order filters on all trips page
=> css filters responsive

src/pages/index.tsx
landing page responsive buttons and video autoplay
=> fix video problem and buttons

src/components/ActivityTable.tsx, src/components/ModalWeb3.tsx, src/components/SendWeb3Transaction.tsx, src/components/TimeLineTrip.tsx, src/pages/_app.tsx
Set up UI/UX to choose between payment methods at the end of the trip detail timeline
=> Payments UI (TripDetail)

src/components/TripCard.tsx, src/controllers/activities.ts, src/pages/trips/create.tsx
Filter in the modal of activities in create trips and fix cities in card of create trips (separe the cities with a '-')
=> Filter active activities in create trip

src/pages/activities/index.tsx
Now, in page all activities, user only can see active activities
=> filter activities by acctive

src/components/ActivityCard.tsx, src/components/ActivityDashboard.tsx, src/components/ActivityDetail.tsx, src/components/Carousel.tsx, src/components/Reviews.tsx, src/components/TimeLineTrip.tsx, src/components/TripCard.tsx, src/components/TripDetail.tsx, src/controllers/activities.ts, src/controllers/trips.ts, src/pages/activities/[id].tsx, src/pages/api/chats/index.tsx, src/pages/api/hello.ts, src/pages/contact/index.tsx, src/pages/home.tsx, src/pages/trips/create.tsx, src/utils/activities.ts, src/utils/web3.ts
erase console.logs and add type in activity dashboard
=> Home activities active

src/components/ActivityCard.tsx, src/components/ActivityDashboard.tsx, src/components/ActivityDetail.tsx, src/components/TripCard.tsx, src/components/TripDetail.tsx, src/pages/user/admin.tsx
details on dashboard activities, capitalize cities, and details css in activity and trips card
=> details in dashboard,trip and act detail

src/controllers/activities.ts, src/controllers/trips.ts
Cambio en los filtros del back para que no reconoscan entre mayusculas y minusculas
=> filtros no descriminan entre mayusculas y minusculas

src/components/ModalWeb3.tsx, src/components/SendWeb3Transaction.tsx, src/components/TimeLineTrip.tsx, src/components/TripDetail.tsx, src/pages/api/payment/web3/index.ts
Added a dependency to TripDetail & TimeLineTrip useEffect that changes after the payment modal is closed
=> update trip detail after web3 payment modal closes

src/pages/trips/index.tsx
change the touppercase to lowerCase
=> fix  city filter

src/components/TripDetail.tsx
=> next share

src/components/CardTimeLine.tsx, src/components/Carousel.tsx, src/components/Loading.tsx, src/components/LoadingWithoutLayout.tsx, src/components/Reviews.tsx, src/components/carouselAvatars.tsx, src/components/layout/Footer.tsx, src/components/layout/Nav.tsx, src/controllers/activities.ts, src/controllers/partials/plantillaEmail.html, src/controllers/trips.ts, src/pages/api/mail/index.tsx, src/pages/chat/[id].tsx, src/pages/index.tsx, src/pages/trips/create.tsx
=> change links of cluodinary
